import json
from pathlib import Path
import numpy as np

# ============================================================
# SETTINGS
# ============================================================

# Project root:
# C:\Users\sahit\Projects\parallel-secure-ycbcr-rf-image-transmission
PROJECT_ROOT = Path(__file__).resolve().parent.parent

# Bitstream JSON generated by imageprocessing
BITSTREAM_JSON = (
    PROJECT_ROOT
    / "imageprocessing"
    / "output"
    / "ycbcr_bitstreams.json"
)


def load_stream_bits():
    """Load Y1, Y2, Y3, Y4, Cb and Cr from the JSON file."""

    if not BITSTREAM_JSON.exists():
        raise FileNotFoundError(
            f"Bitstream JSON not found:\n{BITSTREAM_JSON}"
        )

    with open(BITSTREAM_JSON, "r", encoding="utf-8") as f:
        data = json.load(f)

    streams = data["streams"]

    return {
        "Y1": streams["Y_part1_bits"],
        "Y2": streams["Y_part2_bits"],
        "Y3": streams["Y_part3_bits"],
        "Y4": streams["Y_part4_bits"],
        "Cb": streams["Cb_bits"],
        "Cr": streams["Cr_bits"],
    }


# Load all six streams automatically
STREAM_BITS = load_stream_bits()


SAMPLES_PER_BIT = 160

# Carrier cycles per bit-width. Keeping this fixed means both modulations
# show the SAME carrier frequency: 2 cycles per 4-bit 16-QAM symbol,
# 1 cycle per 2-bit QPSK symbol.
CYCLES_PER_BIT = 0.5

# Number of bits visible at one time
WINDOW_BITS = 12

# Both constellations are scaled to unit average power, so the two
# waveforms are directly comparable on the same amplitude axis.
QAM16_SCALE = 1 / np.sqrt(10)
QPSK_SCALE = 1 / np.sqrt(2)

# Gray-coded 16-QAM levels (2 bits -> one axis)
GRAY_LEVEL = {"00": -3, "01": -1, "11": 1, "10": 3}

MODULATIONS = {
    "16-QAM": {"bits": 4, "points": 16},
    "QPSK": {"bits": 2, "points": 4},
}

# Colors
BG = "#101418"
PANEL = "#141a1f"
GRID = "#263038"
SPINE = "#303a43"
TICK = "#8d98a1"
ACCENT = "#61a8ff"
GREEN = "#5ee7b7"
BTN = "#263b4d"