"""
Reconstruct an RGB image from the simulated/error YCbCr bitstream.

Project structure:

parallel-secure-ycbcr-rf-image-transmission/
│
├── simulator/
│   └── rf_transmission_error_bitstreams.json
│
└── reconstruction/
    └── reconstruct_from_error.py

The reconstruction follows the same pipeline used earlier:

    Y1 + Y2 + Y3 + Y4
            ↓
      1024 × 1024 Y

    Cb 512 × 512 ──→ 2×2 upsample ──→ 1024 × 1024 Cb
    Cr 512 × 512 ──→ 2×2 upsample ──→ 1024 × 1024 Cr

            ↓
       Y + Cb + Cr
            ↓
      BT.601 inverse
            ↓
      1024 × 1024 RGB

The input bitstream is the ERROR bitstream generated by the
RF transmission simulation.

Outputs are saved in this reconstruction folder:

    reconstructed_from_error.png
    reconstructed_Y.png
    reconstructed_Cb_upscaled.png
    reconstructed_Cr_upscaled.png
    reconstruction_metadata.json
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
from PIL import Image


# ============================================================
# PROJECT PATHS
# ============================================================

# This file is located at:
#
# ...\parallel-secure-ycbcr-rf-image-transmission\
#       reconstruction\reconstruct_from_error.py
#
# Therefore:
#
# Path(__file__).resolve().parent
#       = reconstruction
#
# .parent
#       = project root
#
PROJECT_ROOT = Path(__file__).resolve().parent.parent

# Error bitstream generated by the simulator
INPUT_JSON = (
    PROJECT_ROOT
    / "simulator"
    / "rf_transmission_error_bitstreams.json"
)

# Save all reconstructed files here
OUTPUT_DIR = Path(__file__).resolve().parent


# ============================================================
# STREAM NAMES
# ============================================================

STREAM_FIELDS = [
    "Y_part1_bits",
    "Y_part2_bits",
    "Y_part3_bits",
    "Y_part4_bits",
    "Cb_bits",
    "Cr_bits",
]


# ============================================================
# BITSTREAM → 8-BIT SAMPLE
# ============================================================

def bits_to_uint8(
    bits: str,
    expected_samples: int,
    name: str,
) -> np.ndarray:
    """
    Convert an 8-bit-per-sample binary string into uint8 samples.
    """

    if not isinstance(bits, str):
        raise ValueError(
            f"{name}: bitstream is not a string."
        )

    expected_bits = expected_samples * 8

    if len(bits) != expected_bits:
        raise ValueError(
            f"{name}: incorrect bitstream length.\n"
            f"Expected: {expected_bits:,} bits\n"
            f"Received: {len(bits):,} bits"
        )

    if set(bits) - {"0", "1"}:
        raise ValueError(
            f"{name}: bitstream contains characters "
            f"other than 0 and 1."
        )

    # Every sample is exactly 8 bits.
    values = np.fromiter(
        (
            int(bits[i:i + 8], 2)
            for i in range(0, len(bits), 8)
        ),
        dtype=np.uint8,
        count=expected_samples,
    )

    return values


# ============================================================
# LOAD ERROR BITSTREAM
# ============================================================

def load_bitstream() -> dict:
    """
    Load the six error bitstreams generated by the simulator.
    """

    print("=" * 60)
    print("LOADING RF ERROR BITSTREAM")
    print("=" * 60)

    print(f"Input file:")
    print(f"  {INPUT_JSON}")

    if not INPUT_JSON.exists():
        raise FileNotFoundError(
            "\nERROR BITSTREAM NOT FOUND\n\n"
            f"Expected file:\n"
            f"{INPUT_JSON}\n\n"
            "Make sure you run the RF report/error generator first."
        )

    with INPUT_JSON.open(
        "r",
        encoding="utf-8",
    ) as f:
        data = json.load(f)

    if "streams" not in data:
        raise KeyError(
            "The JSON file does not contain a 'streams' object."
        )

    streams = data["streams"]

    for field in STREAM_FIELDS:
        if field not in streams:
            raise KeyError(
                f"Missing stream in JSON: {field}"
            )

    print("Bitstream loaded successfully.")

    return data


# ============================================================
# RECONSTRUCTION
# ============================================================

def reconstruct_image() -> Path:

    data = load_bitstream()

    streams = data["streams"]

    # --------------------------------------------------------
    # IMAGE DIMENSIONS
    # --------------------------------------------------------

    IMAGE_WIDTH = 1024
    IMAGE_HEIGHT = 1024

    # Y contains:
    #
    # 1024 × 1024 = 1,048,576 samples
    #
    # divided into four equal parts:
    #
    # 1,048,576 / 4 = 262,144 samples per part

    Y_TOTAL_SAMPLES = (
        IMAGE_WIDTH * IMAGE_HEIGHT
    )

    Y_PART_SAMPLES = Y_TOTAL_SAMPLES // 4

    # Cb and Cr are 512 × 512 after 2×2 downsampling.

    CHROMA_WIDTH = 512
    CHROMA_HEIGHT = 512

    CHROMA_SAMPLES = (
        CHROMA_WIDTH * CHROMA_HEIGHT
    )

    # --------------------------------------------------------
    # 1. RECONSTRUCT Y
    # --------------------------------------------------------

    print()
    print("=" * 60)
    print("1. RECONSTRUCTING Y")
    print("=" * 60)

    y_parts = []

    for field in STREAM_FIELDS[:4]:

        print(f"Decoding {field}...")

        y_part = bits_to_uint8(
            streams[field],
            Y_PART_SAMPLES,
            field,
        )

        print(
            f"  Samples: {len(y_part):,}"
        )

        y_parts.append(y_part)

    # Put Y1, Y2, Y3 and Y4 back together.

    y_flat = np.concatenate(y_parts)

    if len(y_flat) != Y_TOTAL_SAMPLES:
        raise ValueError(
            "Reconstructed Y does not contain "
            "1,048,576 samples."
        )

    # Restore 1024 × 1024 image.

    Y = y_flat.reshape(
        IMAGE_HEIGHT,
        IMAGE_WIDTH,
    )

    print(
        f"Y reconstructed: "
        f"{Y.shape[1]} × {Y.shape[0]}"
    )

    # --------------------------------------------------------
    # 2. RECONSTRUCT Cb
    # --------------------------------------------------------

    print()
    print("=" * 60)
    print("2. RECONSTRUCTING Cb")
    print("=" * 60)

    Cb_small = bits_to_uint8(
        streams["Cb_bits"],
        CHROMA_SAMPLES,
        "Cb_bits",
    ).reshape(
        CHROMA_HEIGHT,
        CHROMA_WIDTH,
    )

    print(
        f"Cb before upsampling: "
        f"{Cb_small.shape[1]} × {Cb_small.shape[0]}"
    )

    # Earlier pipeline used 2×2 replication.
    #
    # Each 512×512 Cb sample becomes:
    #
    # A A
    # A A

    Cb = np.repeat(
        np.repeat(
            Cb_small,
            2,
            axis=0,
        ),
        2,
        axis=1,
    )

    print(
        f"Cb after upsampling: "
        f"{Cb.shape[1]} × {Cb.shape[0]}"
    )

    # --------------------------------------------------------
    # 3. RECONSTRUCT Cr
    # --------------------------------------------------------

    print()
    print("=" * 60)
    print("3. RECONSTRUCTING Cr")
    print("=" * 60)

    Cr_small = bits_to_uint8(
        streams["Cr_bits"],
        CHROMA_SAMPLES,
        "Cr_bits",
    ).reshape(
        CHROMA_HEIGHT,
        CHROMA_WIDTH,
    )

    print(
        f"Cr before upsampling: "
        f"{Cr_small.shape[1]} × {Cr_small.shape[0]}"
    )

    Cr = np.repeat(
        np.repeat(
            Cr_small,
            2,
            axis=0,
        ),
        2,
        axis=1,
    )

    print(
        f"Cr after upsampling: "
        f"{Cr.shape[1]} × {Cr.shape[0]}"
    )

    # --------------------------------------------------------
    # 4. SAVE Y / Cb / Cr
    # --------------------------------------------------------

    print()
    print("=" * 60)
    print("4. SAVING Y / Cb / Cr")
    print("=" * 60)

    OUTPUT_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    y_path = (
        OUTPUT_DIR
        / "reconstructed_Y.png"
    )

    cb_path = (
        OUTPUT_DIR
        / "reconstructed_Cb_upscaled.png"
    )

    cr_path = (
        OUTPUT_DIR
        / "reconstructed_Cr_upscaled.png"
    )

    Image.fromarray(
        Y,
        mode="L",
    ).save(y_path)

    Image.fromarray(
        Cb,
        mode="L",
    ).save(cb_path)

    Image.fromarray(
        Cr,
        mode="L",
    ).save(cr_path)

    print(f"Y  saved: {y_path}")
    print(f"Cb saved: {cb_path}")
    print(f"Cr saved: {cr_path}")

    # --------------------------------------------------------
    # 5. YCbCr → RGB
    # --------------------------------------------------------

    print()
    print("=" * 60)
    print("5. YCbCr → RGB")
    print("=" * 60)

    # BT.601 full-range inverse equations:
    #
    # R = Y + 1.402(Cr - 128)
    #
    # G = Y - 0.344136(Cb - 128)
    #       - 0.714136(Cr - 128)
    #
    # B = Y + 1.772(Cb - 128)

    Yf = Y.astype(
        np.float32
    )

    Cbf = (
        Cb.astype(np.float32)
        - 128.0
    )

    Crf = (
        Cr.astype(np.float32)
        - 128.0
    )

    R = (
        Yf
        + 1.402 * Crf
    )

    G = (
        Yf
        - 0.344136 * Cbf
        - 0.714136 * Crf
    )

    B = (
        Yf
        + 1.772 * Cbf
    )

    # Stack R, G, B into one image.

    rgb = np.stack(
        [R, G, B],
        axis=2,
    )

    # RGB must remain within 0–255.

    rgb = np.clip(
        np.rint(rgb),
        0,
        255,
    ).astype(np.uint8)

    image = Image.fromarray(
        rgb,
        mode="RGB",
    )

    final_path = (
        OUTPUT_DIR
        / "reconstructed_from_error.png"
    )

    image.save(final_path)

    print()
    print(
        f"RGB reconstructed: "
        f"{IMAGE_WIDTH} × {IMAGE_HEIGHT}"
    )

    print(
        f"Image saved: {final_path}"
    )

    # --------------------------------------------------------
    # 6. SAVE METADATA
    # --------------------------------------------------------

    metadata = {
        "source_bitstream": str(INPUT_JSON),

        "modulation": data.get(
            "modulation",
            "16-QAM",
        ),

        "bits_per_symbol": data.get(
            "bits_per_symbol",
            4,
        ),

        "error_model": data.get(
            "error_model",
            "unknown",
        ),

        "configured_ber": data.get(
            "configured_ber",
        ),

        "random_seed": data.get(
            "random_seed",
        ),

        "dimensions": {
            "Y": [
                1024,
                1024,
            ],
            "Cb_before_upsampling": [
                512,
                512,
            ],
            "Cr_before_upsampling": [
                512,
                512,
            ],
            "Cb_after_upsampling": [
                1024,
                1024,
            ],
            "Cr_after_upsampling": [
                1024,
                1024,
            ],
            "RGB": [
                1024,
                1024,
            ],
        },

        "samples": {
            "Y_total": 1_048_576,
            "Y_per_part": 262_144,
            "Cb": 262_144,
            "Cr": 262_144,
        },

        "bits": {
            "Y1": 2_097_152,
            "Y2": 2_097_152,
            "Y3": 2_097_152,
            "Y4": 2_097_152,
            "Cb": 2_097_152,
            "Cr": 2_097_152,
            "total": 12_582_912,
        },

        "reconstruction": {
            "Y": (
                "Concatenate Y1, Y2, Y3 and Y4 "
                "in their original order, then reshape "
                "to 1024x1024."
            ),

            "Cb": (
                "Decode 512x512 Cb and replicate "
                "each sample into a 2x2 block."
            ),

            "Cr": (
                "Decode 512x512 Cr and replicate "
                "each sample into a 2x2 block."
            ),

            "color_conversion": (
                "BT.601 full-range inverse YCbCr to RGB."
            ),
        },
    }

    metadata_path = (
        OUTPUT_DIR
        / "reconstruction_metadata.json"
    )

    metadata_path.write_text(
        json.dumps(
            metadata,
            indent=2,
        ),
        encoding="utf-8",
    )

    # --------------------------------------------------------
    # FINAL SUMMARY
    # --------------------------------------------------------

    print()
    print("=" * 60)
    print("RECONSTRUCTION COMPLETE")
    print("=" * 60)

    print()
    print("Input:")
    print(f"  {INPUT_JSON}")

    print()
    print("Output folder:")
    print(f"  {OUTPUT_DIR}")

    print()
    print("Generated files:")
    print(f"  {final_path.name}")
    print(f"  {y_path.name}")
    print(f"  {cb_path.name}")
    print(f"  {cr_path.name}")
    print(f"  {metadata_path.name}")

    print()
    print(
        "The RGB image was reconstructed from the "
        "BER-corrupted Y/Cb/Cr bitstreams."
    )

    return final_path


# ============================================================
# MAIN
# ============================================================

if __name__ == "__main__":

    try:
        reconstruct_image()

    except Exception as error:

        print()
        print("=" * 60)
        print("RECONSTRUCTION FAILED")
        print("=" * 60)

        print()
        print(error)

        raise